### ISSUE TITLE
用手机调试USB接口后，没有弹出串口设备

### ISSUE THREAD

**Issue by xcja123** [BbsonLin/serial_port_flutter#1]
![image](https://user-images.githubusercontent.com/34464154/70962649-db1ad580-20c0-11ea-9452-7e19b58717c3.png)

**Comment by BbsonLin** [comment]
@xcja123 可以在詳細的描述你的測試環境嗎?

目前我大部分應用只在 Android 工控機連接 RS232/RS485，
但沒試過 USB 在 Android 工控機或手機的情況。

如果可以你也可以發 PR.

**Comment by xcja123** [comment]
选择DEVICE后显示空白没有弹出可用的串口设备。。。
但是用其他SPU串口软件可以读出相应的串口设备







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Bobson Lin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月23日(星期一) 中午11:28
收件人:&nbsp;"BbsonLin/serial_port_flutter"<serial_port_flutter@noreply.github.com&gt;;
抄送:&nbsp;"421386102"<421386102@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [BbsonLin/serial_port_flutter] 用手机调试USB接口后，没有弹出串口设备 (#1)




@xcja123 可以在詳細的描述你的測試環境嗎?
 
目前我大部分應用只在 Android 工控機連接 RS232/RS485，
 但沒試過 USB 在 Android 工控機或手機的情況。
 
如果可以你也可以發 PR.

**Comment by BbsonLin** [comment]
@xcja123 用 `adb shell` 進入手機後，`ls /dev/` 是有東西的嗎?

**Comment by BbsonLin** [comment]
Temporarily close this issue because of no response so far.
