### ISSUE TITLE
crashed when install

### ISSUE THREAD

**Issue by rickchew** [BbsonLin/serial_port_flutter#2]
Hi Author, thanks for the sample code, i'm new to flutter, i have tried to build with android studio gradle, i think it was a failed build, may i know what is the issue?

Im only able to run in the emulator with this command `flutter run -d --enable-software-rendering` cant run it once i have removed `--enable-software-rendering`

Although it showed the layout but i can't test is the serial command work since i can't install to my real devices

**Comment by rickchew** [comment]
Or can i have the build apk ? i just want to make sure flutter can worked on what i want, i have tried ionic, RN, really appreciate

**Comment by BbsonLin** [comment]
Hi, @rickchew Which type of device are you trying? Do you have any log for removed `--enable-software-rendering` situation?
Do you mean the example's built APK?

**Comment by rickchew** [comment]
i'm running on android 4.1 since my project is to control plotter machine which running android 4.1, error showed Failed to setup Skia Gr context, i have googled and also studied on this [https://github.com/flutter/flutter/issues/11094](url) , but so far no clue at all

Yup, i mean example's built APK, thanks for your respone

**Comment by BbsonLin** [comment]
Hmm.. @rickchew I've checked my Android 4.2.2 device also bumped into this issue.

I add a commit https://github.com/BbsonLin/serial_port_flutter/commit/83808a3af42adb44987ef9da36353ca0ed0743c1. It'll run the app with `enable-software-rendering` tag for those device under Android 5.

Also, I create a release `v0.1.0` with the example built APK. Check out here https://github.com/BbsonLin/serial_port_flutter/releases/tag/v0.1.0

Thanks for the issue report.

**Comment by rickchew** [comment]
Does this mean your sample cannot run below android 5 ? i want to send serial command like echo "mycotent" > /dev/ttyS0 with 115200 baud rate, i have studied your code , seems it match my requirement

**Comment by BbsonLin** [comment]
Yep, I only checked that the sample code could work for Android 5 above. But recently I got an Android 4.2.2 device, I also bumped into this issue.

From my experience, Android 5 below would cause some problems when developing the Flutter app.
Let me know if you have any problems with the latest sample code.
