### ISSUE TITLE
Custom baudrates

### ISSUE THREAD

**Issue by mortenboye** [BbsonLin/serial_port_flutter#5]
Is it possible to open a port with a custom baudrate, like 31500 for midi?

**Comment by BbsonLin** [comment]
Hi @mortenboye , have you tried to set 31500 when using `FlutterSerialPort.createSerialPort(theDevice, baudrate)`?

**Comment by mortenboye** [comment]
Yes, I get an error saying, "unsupported baudrate". So I guess this is an issue on the OS level?

**Comment by BbsonLin** [comment]
Hi @mortenboye.
To solve this problem, I think is modifying low level code in [Android-SerialPort-API](https://github.com/licheedev/Android-SerialPort-API) project. Like [here](https://github.com/licheedev/Android-SerialPort-API/blob/master/serialport/src/main/cpp/SerialPort.c#L34).
There's nothing I can do in my project, sorry bro :(
