### ISSUE TITLE
listDevices can not find new plugin usb serial port device

### ISSUE THREAD

**Issue by lee4git** [BbsonLin/serial_port_flutter#9]
modify  serial_port_flutter/android/src/main/java/com/example/flutter_serial_port/FlutterSerialPortPlugin.java

1.
// private SerialPortFinder mSerialPortFinder = new SerialPortFinder();

2.
private ArrayList<String> getAllDevices() {
    //ArrayList<String> devices = new ArrayList<String>(Arrays.asList(mSerialPortFinder.getAllDevices()));
    ArrayList<String> devices = new ArrayList<String>(Arrays.asList( new SerialPortFinder().getAllDevices()));
    return devices;
  }
3.
  private ArrayList<String> getAllDevicesPath() {
    //ArrayList<String> devicesPath = new ArrayList<String>(Arrays.asList(mSerialPortFinder.getAllDevicesPath()));
ArrayList<String> devicesPath = new ArrayList<String>(Arrays.asList(new SerialPortFinder().getAllDevicesPath()));
    return devicesPath;
  }

**Comment by hakanbakacak** [comment]
After clone the repo, I run the example project and when I click on the devices button in the settings section, I get an exception.
![image](https://user-images.githubusercontent.com/22100241/101163049-3c2a1900-3644-11eb-92ab-d4d3f085f385.png)
The exception I got in the platform_channel.dart file is like this
![image](https://user-images.githubusercontent.com/22100241/101163162-5a901480-3644-11eb-8c99-3a3d54dafb73.png)
Also the find devices function in pub.dev gives this error.
```
Future<List<Device>> findDevices() async {
  return await FlutterSerialPort.listDevices();
}
```

**Comment by BbsonLin** [comment]
Hi @hakanbakacak, Are you running the example app on Windows desktop?

**Comment by hakanbakacak** [comment]
Yes, I am running the example app on Windows desktop. Do you have any suggestions for a solution for this issue?

**Comment by BbsonLin** [comment]
Hi @hakanbakacak, I open another issue for this problem. #10
